<?php

declare(strict_types=1);

return [
    'routes' => [
        ['name' => 'page#index', 'url' => '/', 'verb' => 'GET'],
        ['name' => 'api#health', 'url' => '/api/health', 'verb' => 'GET'],
        ['name' => 'settings#getCompany', 'url' => '/api/settings/company', 'verb' => 'GET'],
        ['name' => 'settings#saveCompany', 'url' => '/api/settings/company', 'verb' => 'PUT'],
        ['name' => 'settings#getTexts', 'url' => '/api/settings/texts', 'verb' => 'GET'],
        ['name' => 'settings#saveTexts', 'url' => '/api/settings/texts', 'verb' => 'PUT'],
        ['name' => 'settings#getTax', 'url' => '/api/settings/tax', 'verb' => 'GET'],
        ['name' => 'settings#saveTax', 'url' => '/api/settings/tax', 'verb' => 'PUT'],
        ['name' => 'settings#getMisc', 'url' => '/api/settings/misc', 'verb' => 'GET'],
        ['name' => 'settings#saveMisc', 'url' => '/api/settings/misc', 'verb' => 'PUT'],
        ['name' => 'settings#getEmailBehavior', 'url' => '/api/settings/email-behavior', 'verb' => 'GET'],
        ['name' => 'settings#saveEmailBehavior', 'url' => '/api/settings/email-behavior', 'verb' => 'PUT'],
        ['name' => 'products#list', 'url' => '/api/products', 'verb' => 'GET'],
        ['name' => 'products#create', 'url' => '/api/products', 'verb' => 'POST'],
        ['name' => 'products#update', 'url' => '/api/products/{id}', 'verb' => 'PUT'],
        ['name' => 'products#destroy', 'url' => '/api/products/{id}', 'verb' => 'DELETE'],
        ['name' => 'fiscalYears#list', 'url' => '/api/fiscal-years', 'verb' => 'GET'],
        ['name' => 'fiscalYears#create', 'url' => '/api/fiscal-years', 'verb' => 'POST'],
        ['name' => 'fiscalYears#update', 'url' => '/api/fiscal-years/{id}', 'verb' => 'PUT'],
        ['name' => 'fiscalYears#destroy', 'url' => '/api/fiscal-years/{id}', 'verb' => 'DELETE'],
        ['name' => 'incomes#list', 'url' => '/api/fiscal-years/{fiscalYearId}/incomes', 'verb' => 'GET'],
        ['name' => 'incomes#create', 'url' => '/api/fiscal-years/{fiscalYearId}/incomes', 'verb' => 'POST'],
        ['name' => 'incomes#update', 'url' => '/api/incomes/{id}', 'verb' => 'PUT'],
        ['name' => 'incomes#destroy', 'url' => '/api/incomes/{id}', 'verb' => 'DELETE'],
        ['name' => 'expenses#list', 'url' => '/api/fiscal-years/{fiscalYearId}/expenses', 'verb' => 'GET'],
        ['name' => 'expenses#create', 'url' => '/api/fiscal-years/{fiscalYearId}/expenses', 'verb' => 'POST'],
        ['name' => 'expenses#update', 'url' => '/api/expenses/{id}', 'verb' => 'PUT'],
        ['name' => 'expenses#destroy', 'url' => '/api/expenses/{id}', 'verb' => 'DELETE'],
        ['name' => 'fiscalReports#gubPdf', 'url' => '/api/fiscal-years/{id}/gub/pdf', 'verb' => 'GET'],
        ['name' => 'customers#list', 'url' => '/api/customers', 'verb' => 'GET'],
        ['name' => 'customers#create', 'url' => '/api/customers', 'verb' => 'POST'],
        ['name' => 'customers#update', 'url' => '/api/customers/{id}', 'verb' => 'PUT'],
        ['name' => 'customers#destroy', 'url' => '/api/customers/{id}', 'verb' => 'DELETE'],
        ['name' => 'cases#list', 'url' => '/api/cases', 'verb' => 'GET'],
        ['name' => 'cases#create', 'url' => '/api/cases', 'verb' => 'POST'],
        ['name' => 'cases#update', 'url' => '/api/cases/{id}', 'verb' => 'PUT'],
        ['name' => 'cases#destroy', 'url' => '/api/cases/{id}', 'verb' => 'DELETE'],
        ['name' => 'caseElements#list', 'url' => '/api/cases/{caseId}/elements', 'verb' => 'GET'],
        ['name' => 'caseElements#create', 'url' => '/api/cases/{caseId}/elements', 'verb' => 'POST'],
        ['name' => 'caseElements#update', 'url' => '/api/case-elements/{id}', 'verb' => 'PUT'],
        ['name' => 'caseElements#destroy', 'url' => '/api/case-elements/{id}', 'verb' => 'DELETE'],
        ['name' => 'offers#list', 'url' => '/api/offers', 'verb' => 'GET'],
        ['name' => 'offers#show', 'url' => '/api/offers/{id}', 'verb' => 'GET'],
        ['name' => 'offers#create', 'url' => '/api/offers', 'verb' => 'POST'],
        ['name' => 'offers#update', 'url' => '/api/offers/{id}', 'verb' => 'PUT'],
        ['name' => 'offers#destroy', 'url' => '/api/offers/{id}', 'verb' => 'DELETE'],
        ['name' => 'offers#pdf', 'url' => '/api/offers/{id}/pdf', 'verb' => 'GET'],
        ['name' => 'offers#sendEmail', 'url' => '/api/offers/{id}/send-email', 'verb' => 'POST'],
        ['name' => 'offerItems#list', 'url' => '/api/offers/{offerId}/items', 'verb' => 'GET'],
        ['name' => 'offerItems#create', 'url' => '/api/offers/{offerId}/items', 'verb' => 'POST'],
        ['name' => 'offerItems#update', 'url' => '/api/offer-items/{id}', 'verb' => 'PUT'],
        ['name' => 'offerItems#destroy', 'url' => '/api/offer-items/{id}', 'verb' => 'DELETE'],
        ['name' => 'invoices#list', 'url' => '/api/invoices', 'verb' => 'GET'],
        ['name' => 'invoices#show', 'url' => '/api/invoices/{id}', 'verb' => 'GET'],
        ['name' => 'invoices#create', 'url' => '/api/invoices', 'verb' => 'POST'],
        ['name' => 'invoices#update', 'url' => '/api/invoices/{id}', 'verb' => 'PUT'],
        ['name' => 'invoices#destroy', 'url' => '/api/invoices/{id}', 'verb' => 'DELETE'],
        ['name' => 'invoices#pdf', 'url' => '/api/invoices/{id}/pdf', 'verb' => 'GET'],
        ['name' => 'invoices#sendEmail', 'url' => '/api/invoices/{id}/send-email', 'verb' => 'POST'],
        ['name' => 'invoiceItems#list', 'url' => '/api/invoices/{invoiceId}/items', 'verb' => 'GET'],
        ['name' => 'invoiceItems#create', 'url' => '/api/invoices/{invoiceId}/items', 'verb' => 'POST'],
        ['name' => 'invoiceItems#update', 'url' => '/api/invoice-items/{id}', 'verb' => 'PUT'],
        ['name' => 'invoiceItems#destroy', 'url' => '/api/invoice-items/{id}', 'verb' => 'DELETE'],
        ['name' => 'page#spa', 'url' => '/{path}', 'verb' => 'GET', 'requirements' => ['path' => '.*']],
    ],
];
